// Sidebar wordt autogenereerd uit de docs/-mapstructuur (per sectie een map met
// _category_.json). Nieuwe pagina's = bestand droppen in de juiste map.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
