services:
  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  woo-klant-a:
    image: ghcr.io/conductionnl/woo-website-v2
    restart: always
    environment:
      - UPSTREAM_BASE=http://192.168.178.51/apps/opencatalogi/api
      - UPSTREAM_HOST=klant-a.westerweel.work

  woo-klant-b:
    image: ghcr.io/conductionnl/woo-website-v2
    restart: always
    environment:
      - UPSTREAM_BASE=http://192.168.178.52/apps/opencatalogi/api
      - UPSTREAM_HOST=klant-b.westerweel.work

  woo-klant-c:
    image: ghcr.io/conductionnl/woo-website-v2
    restart: always
    environment:
      - UPSTREAM_BASE=http://192.168.178.53/apps/opencatalogi/api
      - UPSTREAM_HOST=klant-c.westerweel.work

volumes:
  caddy_data:
  caddy_config:
