apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordsworth
resources:
  - configmap.yaml
  - init-job.yaml
  - api.yaml
  - api-tailscale.yaml
  - api-tailscale-https.yaml
  - corpus-pvc.yaml
