apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wanderer
resources:
  - pvc.yaml
  - schedules.yaml
  - config.yaml
  - deployment.yaml
  - tailscale.yaml
  - tunnel.yaml
  - standards-feed.yaml
