apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wanderer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/MWest2020/homelab.git
    targetRevision: main
    path: cluster-config/infra/wanderer
  destination:
    server: https://kubernetes.default.svc
    namespace: wanderer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
